### ISSUE TITLE
Top bar/click targets misaligned

### ISSUE THREAD

**Issue by ocdtrekkie** [cem/dillinger-sandstorm#1]
![dillingertest](https://cloud.githubusercontent.com/assets/4399499/10979022/b38fdeb8-83bf-11e5-9aae-834873465572.png)

Looks like for me, there's whitespace above the top bar, but the click targets for the buttons on the bar did not move. I have to click ABOVE the links on the top bar to hit them.

**Comment by cem** [comment]
What's your browser? Also, do you observer this behavior on http://dillinger.io/ ?

**Comment by ocdtrekkie** [comment]
@cem I am the resident "I will break your app because I use Edge" expert.

Dillinger.io is aligned correctly.

**Comment by cem** [comment]
IE bug due to iframes :/

I'll add a workaround.

**Comment by cem** [comment]
Should be fixed as of 68dd138e056124595481f1d8f643f045c839736d
