### ISSUE TITLE
set focus on text input field upon instance creation

### ISSUE THREAD

**Issue by jadeqwang** [cem/dillinger-sandstorm#3]
It would be great if, upon creating a new document, focus is on the text editor on the left side. :)

That way, I can just start typing right away, without having to take a second to think about which side I need to click on, and then click on the field, and then type.

**Comment by cem** [comment]
Should be fixed as of c370c45a5f8dcbc2d844f271e40034ee15fbd1b2 (the version on sandstorm already has this fix)
